spring:
  application:
    name: bidwin-back
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/bidwin?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update

app:
  password-reset:
    url: ${PASSWORD_RESET_URL:http://localhost:5173/password-reset}
  email-verification:
    url: ${EMAIL_VERIFICATION_URL:http://localhost:5173/email-verification}
