global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: bidwin-back
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["server:9090"]

  - job_name: observability
    static_configs:
      - targets:
          - alloy:12345
          - grafana:3000
          - loki:3100
